spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: '{cipher}c64f301ed42aebb35a4b0ea1bf4944193f3229cf930163a481044bd6c5e000d0'
    url: jdbc:postgresql://localhost:5432/student_database
  sql:
    init:
      platform: postgres
