my:
  greeting: hello world from config server
  list:
    value: one, two, three

server:
  port: 8882

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: {cipher}ec332689e829519c912580a3efeb964fbd8394f32c31865b522ba400ea2b4acc
    url: jdbc:postgresql://localhost:5432/student_database
  sql:
    init:
      platform: postgres
