spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: '{cipher}AYBMRmgndYn+/L+aAqJapP/uAMsKoexXFQXGciy1/lQnRLGvUQAB0Zy8CEE9JaFQasWsCL6AwigVoNpgw/72Usy1qVpW5LBRcwZ6gNspcaXnW6lLk+/7cS7xYbPhIzmkbRJowSi4rZyH7CpewnZ+SOpyF3gr1a1BtG/aMTWe4FrYoXGqkjTSrFv71OWBre7k1DS7GOnlZAx8bo1F5CoxXN2BN0DZpc/2pkwWtMiBvaHIXZ9rvQnXU31hRavUdVAa0T2kiyedFYLidiOejRWOlFGkDUf9nXXru97gupFXlVRdUjCQJBMD5ko2LCjgyhtGQgcnK0xXbXIcbUfu3J75aK76BYqMP+6n6Cq7qvV3kbUFZg0FfR5GXxi0AXejpk3IiXwh8aKI+m0rWSh90ybcUKJ8Q/jKEc3ciArcR59D7UaPmj75hV+Mg61rKZmWlyNOicoPgiIBOoNf7YSs3R8clbuGVuvgeN35cQQ5A+Xp7woZwa5MHuihuXkUC+3wiDRtObz1ujOJHPFHo1DXmwz3Pq5W3KzLSULDemAhOve3g7zNGg=='
    url: jdbc:postgresql://localhost:5432/student_database
  sql:
    init:
      platform: postgres
